name: root
channels:
- conda-forge
- anaconda
- bioconda
- defaults
dependencies:
- graphviz=2.38.0=4
- htslib=1.4=0
- libffi=3.2.1=1
- libsequence=1.9.1=1
- pylibseq=0.1.9.post0=py36_0
- r-stringr=1.1.0=r3.3.1_0
- rpy2=2.7.8=py36r3.3.1_1
- tbb=4.4_20150728=0
- ipywidgets=7.0.1=py_2
- lime=0.1.1.18=py36_0
- _license=1.1=py36_1
- alabaster=0.7.9=py36_0
- anaconda-client=1.6.0=py36_0
- anaconda=custom=py36_0
- anaconda-navigator=1.5.0=py36_0
- anaconda-project=0.4.1=py36_0
- appnope=0.1.0=py36_0
- appscript=1.0.1=py36_0
- astroid=1.4.9=py36_0
- astropy=2.0.2=py36hf79c81d_4
- babel=2.3.4=py36_0
- backports=1.0=py36_0
- beautifulsoup4=4.5.3=py36_0
- bitarray=0.8.1=py36_0
- blaze=0.10.1=py36_0
- bokeh=0.12.4=py36_0
- boto=2.45.0=py36_0
- bottleneck=1.2.1=py36hbd380ad_0
- bzip2=1.0.6=3
- cairo=1.14.8=0
- cffi=1.9.1=py36_0
- chardet=2.3.0=py36_0
- chest=0.2.3=py36_0
- click=6.7=py36_0
- cloog=0.18.0=0
- cloudpickle=0.2.2=py36_0
- clyent=1.2.2=py36_0
- colorama=0.3.7=py36_0
- conda=4.3.30=py36h173c244_0
- conda-env=2.6.0=h36134e3_0
- configobj=5.0.6=py36_0
- contextlib2=0.5.4=py36_0
- cryptography=1.7.1=py36_0
- curl=7.52.1=0
- cycler=0.10.0=py36_0
- cython=0.25.2=py36_0
- cytoolz=0.8.2=py36_0
- dask=0.16.0=py36h40f4302_0
- dask-core=0.16.0=py36haa8de34_0
- datashape=0.5.4=py36_0
- decorator=4.0.11=py36_0
- dill=0.2.5=py36_0
- distributed=1.20.1=py36hfc895bc_0
- docutils=0.13.1=py36_0
- entrypoints=0.2.2=py36_0
- et_xmlfile=1.0.1=py36_0
- fastcache=1.0.2=py36_1
- flask=0.12=py36_0
- flask-cors=3.0.2=py36_0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- gcc=4.8.5=8
- get_terminal_size=1.0.0=py36_0
- gettext=0.19.8=1
- gevent=1.2.1=py36_0
- glib=2.50.2=1
- gmp=6.1.0=0
- greenlet=0.4.11=py36_0
- gsl=2.2.1=0
- h5py=2.7.0=np112py36_0
- harfbuzz=0.9.39=2
- hdf5=1.8.17=1
- heapdict=1.0.0=py36_1
- icu=54.1=0
- idna=2.2=py36_0
- imageio=2.2.0=py36h5e01289_0
- imagesize=0.7.1=py36_0
- ipykernel=4.5.2=py36_0
- ipython=6.1.0=py36_0
- ipython_genutils=0.1.0=py36_0
- isl=0.12.2=1
- isort=4.2.5=py36_0
- itsdangerous=0.24=py36_0
- jbig=2.1=0
- jdcal=1.3=py36_0
- jedi=0.10.2=py36_2
- jinja2=2.9.4=py36_0
- jpeg=9b=0
- jsonschema=2.5.1=py36_0
- jupyter=1.0.0=py36_3
- jupyter_client=4.4.0=py36_0
- jupyter_console=5.0.0=py36_0
- jupyter_core=4.2.1=py36_0
- keras=2.0.8=py36h39110e4_0
- lazy-object-proxy=1.2.2=py36_0
- libcxx=4.0.1=h579ed51_0
- libcxxabi=4.0.1=hebd6815_0
- libgcc=4.8.5=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libprotobuf=3.2.0=0
- libtiff=4.0.6=3
- libxml2=2.9.4=0
- libxslt=1.1.29=0
- llvmlite=0.19.0=py36_0
- locket=0.2.0=py36_1
- lxml=3.7.2=py36_0
- markupsafe=0.23=py36_2
- matplotlib=2.0.2=np112py36_0
- mistune=0.7.3=py36_1
- mkl=2017.0.1=0
- mkl-service=1.1.2=py36_3
- mpc=1.0.3=0
- mpfr=3.1.5=0
- mpmath=0.19=py36_1
- msgpack-python=0.4.8=py36h46767b2_0
- multipledispatch=0.4.9=py36_0
- nbconvert=4.2.0=py36_0
- nbformat=4.2.0=py36_0
- ncurses=5.9=10
- networkx=1.11=py36_0
- nltk=3.2.2=py36_0
- nose=1.3.7=py36_1
- notebook=5.0.0=py36_0
- numba=0.34.0=np112py36_0
- numexpr=2.6.2=np112py36_0
- numpy=1.12.1=py36_0
- numpydoc=0.6.0=py36_0
- odo=0.5.0=py36_1
- openpyxl=2.4.1=py36_0
- openssl=1.0.2k=1
- pandas=0.21.0=py36hfed917e_1
- pango=1.40.3=1
- partd=0.3.8=py36hf5c4cb8_0
- path.py=10.0=py36_0
- pathlib2=2.2.0=py36_0
- patsy=0.4.1=py36_0
- pcre=8.39=1
- pep8=1.7.0=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pillow=4.0.0=py36_0
- pip=9.0.1=py36_1
- pixman=0.34.0=0
- plotly=2.0.11=py36_0
- ply=3.9=py36_0
- prompt_toolkit=1.0.9=py36_0
- protobuf=3.2.0=py36_0
- psutil=5.0.1=py36_0
- ptyprocess=0.5.1=py36_0
- py=1.4.32=py36_0
- pyasn1=0.1.9=py36_0
- pycosat=0.6.1=py36_1
- pycparser=2.17=py36_0
- pycrypto=2.6.1=py36_4
- pycurl=7.43.0=py36_2
- pydot=1.2.3=py36h7cb6b2e_0
- pyflakes=1.5.0=py36_0
- pygments=2.1.3=py36_0
- pylint=1.6.4=py36_1
- pyopenssl=16.2.0=py36_0
- pyparsing=2.1.4=py36_0
- pyqt=5.6.0=py36_1
- pytables=3.4.2=np112py36_0
- pytest=3.0.5=py36_0
- python=3.6.0=0
- python-dateutil=2.6.0=py36_0
- python-graphviz=0.5.2=py36_0
- python.app=1.2=py36_4
- pytz=2016.10=py36_0
- pywavelets=0.5.2=py36h2710a04_0
- pyyaml=3.12=py36_0
- pyzmq=16.0.2=py36_0
- qt=5.6.2=0
- qtawesome=0.4.3=py36_0
- qtconsole=4.2.1=py36_1
- qtpy=1.2.1=py36_0
- r=3.3.1=r3.3.1_0
- r-base=3.3.1=0
- r-base64enc=0.1_3=r3.3.1_0
- r-boot=1.3_18=r3.3.1_0
- r-class=7.3_14=r3.3.1_0
- r-cluster=2.0.4=r3.3.1_0
- r-codetools=0.2_14=r3.3.1_0
- r-crayon=1.3.1=r3.3.1_0
- r-digest=0.6.9=r3.3.1_0
- r-evaluate=0.9=r3.3.1_0
- r-foreign=0.8_66=r3.3.1_0
- r-irdisplay=0.4.3=r3.3.1_2
- r-irkernel=0.7=r3.3.1_2
- r-jsonlite=0.9.22=r3.3.1_0
- r-kernsmooth=2.23_15=r3.3.1_0
- r-lattice=0.20_33=r3.3.1_0
- r-magrittr=1.5=r3.3.1_2
- r-mass=7.3_45=r3.3.1_0
- r-matrix=1.2_6=r3.3.1_0
- r-memoise=1.0.0=r3.3.1_0
- r-mgcv=1.8_12=r3.3.1_0
- r-nlme=3.1_128=r3.3.1_0
- r-nnet=7.3_12=r3.3.1_0
- r-pbdzmq=0.2_3=r3.3.1_0
- r-r6=2.1.2=r3.3.1_0
- r-recommended=3.3.1=r3.3.1_0
- r-repr=0.7=r3.3.1_0
- r-rpart=4.1_10=r3.3.1_0
- r-spatial=7.3_11=r3.3.1_0
- r-stringi=1.1.1=r3.3.1_0
- r-survival=2.39_4=r3.3.1_0
- r-uuid=0.1_2=r3.3.1_0
- readline=6.2=2
- redis=3.2.0=0
- redis-py=2.10.5=py36_0
- requests=2.12.4=py36_0
- rope=0.9.4=py36_1
- ruamel_yaml=0.11.14=py36_1
- scikit-image=0.13.1=py36hd1453f6_0
- scikit-learn=0.19.0=np112py36_0
- scipy=0.19.1=np112py36_0
- seaborn=0.7.1=py36_0
- setuptools=27.2.0=py36_0
- simplegeneric=0.8.1=py36_1
- singledispatch=3.4.0.3=py36_0
- sip=4.18=py36_0
- six=1.10.0=py36_0
- snowballstemmer=1.2.1=py36_0
- sockjs-tornado=1.0.3=py36_0
- sortedcontainers=1.5.7=py36ha982688_0
- sphinx=1.5.1=py36_0
- spyder=3.1.2=py36_0
- sqlalchemy=1.1.5=py36_0
- sqlite=3.13.0=0
- statsmodels=0.8.0=py36h9c68fc9_0
- sympy=1.0=py36_0
- tblib=1.3.2=py36hda67792_0
- tensorflow=1.1.0=np112py36_0
- terminado=0.6=py36_0
- tk=8.5.18=0
- toolz=0.8.2=py36_0
- tornado=4.5.2=py36h468dda9_0
- traitlets=4.3.1=py36_0
- unicodecsv=0.14.1=py36_0
- wcwidth=0.1.7=py36_0
- werkzeug=0.11.15=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=3.0.2=py36_0
- wrapt=1.10.8=py36_0
- xlrd=1.0.0=py36_0
- xlsxwriter=0.9.6=py36_0
- xlwings=0.10.2=py36_0
- xlwt=1.2.0=py36_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zeromq=4.1.3=0
- zict=0.1.3=py36h71da714_0
- zlib=1.2.8=3
- pip:
  - appdirs==1.4.3
  - backports.shutil-get-terminal-size==1.0.0
  - brewer2mpl==1.4.1
  - cppimport==16.6.24
  - django==1.11.3
  - et-xmlfile==1.0.1
  - facets==1.1.0
  - fwdpy11==0.1.2a0
  - ggplot==0.11.5
  - html5lib==0.999999999
  - ipython-genutils==0.2.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.1
  - mako==1.0.6
  - packaging==16.8
  - prompt-toolkit==1.0.14
  - pybind11==2.1.1
  - rope-py3k==0.9.4.post1
  - tables==3.4.2
  - webencodings==0.5.1

